name: EnglisHub

services:
  django-dev:
    image: django-dev
    ports:
      - 8000:8000
    networks:
      - back-tier
    volumes:
      - ../EnglisHubDjango:/app
    depends_on:
      - mariadb
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: sh -c "gunicorn englishubdjango.wsgi:application -b 0.0.0.0:8000 --reload"
    # --reload sadece geliştirme içindir, prod ortamında kaldırın

  angular-dev:
    image: angular-dev
    ports:
      - 4200:4200
    networks:
      - front-tier
    volumes:
      - ../EnglisHubAngular/englishubangular:/app
    working_dir: /app
    command: sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    # Geliştirme için Angular servisidir

  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - front-tier
      - back-tier
    depends_on:
      - django-dev
    volumes:
      - ../EnglisHubAngular/englishubangular/dist/englishubangular:/usr/share/nginx/html
      - ../../Common/Documentation/documentation/site:/usr/share/nginx/documentation
      - ./dev-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # Angular'ın build çıktısı burada servis edilir

  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - back-tier

  mkdocs:
    image: mkdocs
    ports:
      - 9000:9000
    networks:
      - front-tier
    volumes:
      - ../../Common/Documentation/documentation:/app
    command: mkdocs serve -a 0.0.0.0:9000

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge